import "server-only";
import { spawn } from "node:child_process";
import { existsSync, mkdirSync } from "node:fs";
import { writeFile, chmod, readdir, rm } from "node:fs/promises";
import { join, resolve, sep } from "node:path";
import { validateName } from "@/lib/registry/repos";
import { getEnv } from "@/lib/env";

/**
 * Resolve the bare-repo storage root. Lazy: never call getEnv() at
 * module load — `next build` collects page data in NODE_ENV=production
 * and would otherwise trip the production env validator with the dev
 * config still in scope.
 */
export function getGitDataDir(): string {
  return getEnv().gitDataDir;
}

/**
 * Resolve the on-disk path of a bare repository, asserting that the
 * resolved path stays inside `gitDataDir`. This is the only place that
 * turns user-supplied {owner, name} into a filesystem path; it MUST be
 * called from anywhere that needs to construct one, to prevent
 * directory-traversal attacks.
 */
export function repoPath(owner: string, name: string): string {
  validateName(owner, "owner");
  validateName(name, "repo");
  const root = getGitDataDir();
  const path = resolve(root, owner, `${name}.git`);
  const rootWithSep = root.endsWith(sep) ? root : root + sep;
  if (!path.startsWith(rootWithSep)) {
    throw new Error(
      `repoPath resolved outside gitDataDir (owner=${owner} name=${name})`,
    );
  }
  return path;
}

/**
 * Create a bare git repository at the canonical path, plus a post-receive
 * hook that calls back into the bridge so the PagesPublisher can pick up
 * changes. Idempotent: if the bare repo already exists, this is a no-op
 * for `git init`, but the hook is re-rendered to keep it in sync with
 * config changes.
 */
export async function createBareRepo(owner: string, name: string): Promise<void> {
  const path = repoPath(owner, name);
  const root = getGitDataDir();
  if (!existsSync(root)) mkdirSync(root, { recursive: true });

  await runGit(["init", "--bare", "--initial-branch=main", path]);
  await installPostReceiveHook(path, owner, name);
}

/**
 * Remove the bare repository from disk. Idempotent — missing directory
 * is not an error. The repoPath() call asserts the resolved path stays
 * inside gitDataDir, so this cannot wander out of the data root.
 */
export async function deleteBareRepo(owner: string, name: string): Promise<void> {
  const path = repoPath(owner, name);
  await rm(path, { recursive: true, force: true });
}

/**
 * Reinstall the post-receive hook for every existing repo. Called from
 * the startup reconciler so a rotated BRIDGE_HOOK_SECRET / changed
 * callback URL propagates without forcing operators to re-create repos.
 */
export async function reinstallAllHooks(): Promise<{ count: number }> {
  const root = getGitDataDir();
  if (!existsSync(root)) return { count: 0 };
  let count = 0;
  const owners = await readdir(root, { withFileTypes: true });
  for (const ownerEnt of owners) {
    if (!ownerEnt.isDirectory()) continue;
    const ownerDir = join(root, ownerEnt.name);
    const repos = await readdir(ownerDir, { withFileTypes: true });
    for (const repoEnt of repos) {
      if (!repoEnt.isDirectory() || !repoEnt.name.endsWith(".git")) continue;
      const repoName = repoEnt.name.replace(/\.git$/, "");
      try {
        await installPostReceiveHook(
          join(ownerDir, repoEnt.name),
          ownerEnt.name,
          repoName,
        );
        count += 1;
      } catch (e) {
        console.warn(
          `[backend] failed to reinstall hook for ${ownerEnt.name}/${repoName}:`,
          e,
        );
      }
    }
  }
  return { count };
}

async function installPostReceiveHook(
  bareRepoPath: string,
  owner: string,
  name: string,
): Promise<void> {
  const hookPath = join(bareRepoPath, "hooks", "post-receive");
  const env = getEnv();
  const callbackUrl = env.postReceiveCallbackUrl;
  const hookSecret = env.hookSecret;

  // Escape any quotes in owner/name (validation already enforces a safe
  // charset, but defense in depth is cheap).
  const safeOwner = owner.replace(/"/g, "");
  const safeName = name.replace(/"/g, "");
  const safeSecret = hookSecret.replace(/'/g, "");

  // The hook computes HMAC-SHA256 over the JSON body with the per-bridge
  // secret and sends it in X-Bridge-Hmac. The bridge constant-time
  // verifies before processing. Reading the secret from a variable in
  // this script (rather than baking it into args via `-d`) keeps it out
  // of process listings on the hook side. We DO bake the URL in.
  const script = `#!/bin/sh
# Auto-generated by codespaces/src/lib/git/backend.ts
# Posts each updated ref to the bridge so it can run the Pages publisher.
# The bridge verifies X-Bridge-Hmac (sha256 of body keyed by the per-bridge
# secret) — see src/app/api/git/internal/post-receive/route.ts.

set -u
BRIDGE_HOOK_SECRET='${safeSecret}'

while read oldrev newrev refname; do
  body=$(printf '{"owner":"%s","repo":"%s","ref":"%s","oldRev":"%s","newRev":"%s"}' \\
    "${safeOwner}" "${safeName}" "$refname" "$oldrev" "$newrev")
  sig=$(printf '%s' "$body" | openssl dgst -sha256 -hmac "$BRIDGE_HOOK_SECRET" -hex 2>/dev/null | awk '{print $NF}')
  curl -fsS -X POST -H "Content-Type: application/json" \\
    -H "X-Bridge-Hmac: sha256=$sig" \\
    --data-binary "$body" \\
    "${callbackUrl}" >/dev/null \\
    || echo "post-receive: callback to bridge failed" >&2
done
`;

  await writeFile(hookPath, script, "utf-8");
  await chmod(hookPath, 0o755);
}

function runGit(args: string[]): Promise<void> {
  return new Promise((resolveFn, rejectFn) => {
    const child = spawn("git", args, { stdio: ["ignore", "pipe", "pipe"] });
    let stderr = "";
    child.stderr.on("data", (d) => (stderr += d.toString()));
    child.on("error", rejectFn);
    child.on("close", (code) => {
      if (code === 0) resolveFn();
      else rejectFn(new Error(`git ${args.join(" ")} exited ${code}: ${stderr}`));
    });
  });
}

/**
 * Sum the on-disk bytes of a bare repo. Uses `du -sb` for accuracy
 * (matches what the operator sees on `df`); on macOS — which lacks the
 * GNU `-b` flag — we fall back to `du -sk` and convert to bytes. Result
 * is cached per (owner, repo) for 60s so a push burst doesn't hammer
 * the filesystem.
 */
const diskSizeCache = new Map<string, { bytes: number; expires: number }>();
const DISK_SIZE_TTL_MS = 60 * 1000;

export function getRepoDiskBytes(
  owner: string,
  name: string,
): Promise<number> {
  const key = `${owner}/${name}`;
  const now = Date.now();
  const cached = diskSizeCache.get(key);
  if (cached && cached.expires > now) return Promise.resolve(cached.bytes);

  const path = repoPath(owner, name);
  return new Promise((resolveFn) => {
    const isLinux = process.platform === "linux";
    const args = isLinux ? ["-sb", path] : ["-sk", path];
    const child = spawn("du", args, { stdio: ["ignore", "pipe", "pipe"] });
    let stdout = "";
    child.stdout.on("data", (d) => (stdout += d.toString()));
    child.on("error", () => resolveFn(0));
    child.on("close", () => {
      const first = stdout.trim().split(/\s+/)[0] ?? "0";
      const raw = Number(first);
      const bytes = Number.isFinite(raw) ? (isLinux ? raw : raw * 1024) : 0;
      diskSizeCache.set(key, { bytes, expires: now + DISK_SIZE_TTL_MS });
      resolveFn(bytes);
    });
  });
}

/**
 * Read the commit SHA at the tip of `branch` in the bare repo. Returns
 * null when the ref doesn't exist (newly created repo, never pushed),
 * which the reconciler treats as "nothing to publish yet" rather than a
 * drift signal.
 */
export function readBranchHead(
  owner: string,
  name: string,
  branch: string,
): Promise<string | null> {
  if (!/^[A-Za-z0-9._/-]+$/.test(branch)) {
    return Promise.reject(
      new Error(`refusing unsafe branch name ${JSON.stringify(branch)}`),
    );
  }
  const repo = repoPath(owner, name);
  return new Promise((resolveFn) => {
    const child = spawn(
      "git",
      ["-C", repo, "rev-parse", "--verify", `refs/heads/${branch}`],
      { stdio: ["ignore", "pipe", "pipe"] },
    );
    let stdout = "";
    child.stdout.on("data", (d) => (stdout += d.toString()));
    child.on("error", () => resolveFn(null));
    child.on("close", (code) => {
      if (code === 0) {
        const sha = stdout.trim();
        resolveFn(/^[0-9a-f]{40}$/.test(sha) ? sha : null);
      } else {
        resolveFn(null);
      }
    });
  });
}
